"""Motor de sesiones: máquina de estados pura, sin transporte ni persistencia."""

from .modelo import (
    AUSENCIA,
    CIERRE_SISTEMA,
    COMPLETA,
    EN_CURSO,
    INCONSISTENTE,
    RELEVO,
    SEVERIDADES,
    Alarma,
    Config,
    CrearSesion,
    Evento,
    FinalizarSesion,
    MarcarActividad,
    MarcarAlarmadaPuertaAbierta,
    MarcarInconsistente,
    RegistrarAcceso,
    RegistrarArmario,
    RegistrarPir,
    RegistrarPuerta,
    Sesion,
)
from .motor import decidir

__all__ = [
    "AUSENCIA",
    "CIERRE_SISTEMA",
    "COMPLETA",
    "EN_CURSO",
    "INCONSISTENTE",
    "RELEVO",
    "SEVERIDADES",
    "Alarma",
    "Config",
    "CrearSesion",
    "Evento",
    "FinalizarSesion",
    "MarcarActividad",
    "MarcarAlarmadaPuertaAbierta",
    "MarcarInconsistente",
    "RegistrarAcceso",
    "RegistrarArmario",
    "RegistrarPir",
    "RegistrarPuerta",
    "Sesion",
    "decidir",
]
